// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:hanyin_printer_fluttify/src/ios/ios.export.g.dart';
import 'package:hanyin_printer_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

class com_getkeepsafe_relinker_ApkLibraryInstaller extends java_lang_Object with com_getkeepsafe_relinker_ReLinker_LibraryInstaller {
  //region constants
  
  //endregion

  //region creators
  static Future<com_getkeepsafe_relinker_ApkLibraryInstaller> create__() async {
    final int refId = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('ObjectFactory::createcom_getkeepsafe_relinker_ApkLibraryInstaller__');
    final object = com_getkeepsafe_relinker_ApkLibraryInstaller()..refId = refId..tag = 'hanyin_printer_fluttify';
  
    kNativeObjectPool.add(object);
    return object;
  }
  
  static Future<List<com_getkeepsafe_relinker_ApkLibraryInstaller>> create_batch__(int length) async {
    // if (#__check_param_size__#) {
    //   return Future.error('all args must has same length!');
    // }
    final List resultBatch = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('ObjectFactory::create_batchcom_getkeepsafe_relinker_ApkLibraryInstaller__', {'length': length});
  
    final List<com_getkeepsafe_relinker_ApkLibraryInstaller> typedResult = resultBatch.map((result) => com_getkeepsafe_relinker_ApkLibraryInstaller()..refId = result..tag = 'hanyin_printer_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  //endregion

  //region getters
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  
  //endregion
}

extension com_getkeepsafe_relinker_ApkLibraryInstaller_Batch on List<com_getkeepsafe_relinker_ApkLibraryInstaller> {
  //region getters
  
  //endregion

  //region methods
  
  //endregion
}