// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:hanyin_printer_fluttify/src/ios/ios.export.g.dart';
import 'package:hanyin_printer_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'package:foundation_fluttify/foundation_fluttify.dart';

class com_getkeepsafe_relinker_ReLinker extends java_lang_Object  {
  //region constants
  
  //endregion

  //region creators
  
  //endregion

  //region getters
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  static Future<void> loadLibrary__android_content_Context__String(android_content_Context var0, String var1) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.getkeepsafe.relinker.ReLinker::loadLibrary([\'var1\':$var1])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('com.getkeepsafe.relinker.ReLinker::loadLibrary__android_content_Context__String', {"var0": var0.refId, "var1": var1});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  static Future<void> loadLibrary__android_content_Context__String__String(android_content_Context var0, String var1, String var2) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.getkeepsafe.relinker.ReLinker::loadLibrary([\'var1\':$var1, \'var2\':$var2])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('com.getkeepsafe.relinker.ReLinker::loadLibrary__android_content_Context__String__String', {"var0": var0.refId, "var1": var1, "var2": var2});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  static Future<void> loadLibrary__android_content_Context__String__com_getkeepsafe_relinker_ReLinker_LoadListener(android_content_Context var0, String var1, com_getkeepsafe_relinker_ReLinker_LoadListener var2) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.getkeepsafe.relinker.ReLinker::loadLibrary([\'var1\':$var1])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('com.getkeepsafe.relinker.ReLinker::loadLibrary__android_content_Context__String__com_getkeepsafe_relinker_ReLinker_LoadListener', {"var0": var0.refId, "var1": var1});
  
  
    // handle native call
    MethodChannel('com.getkeepsafe.relinker.ReLinker::loadLibrary__android_content_Context__String__com_getkeepsafe_relinker_ReLinker_LoadListener::Callback')
        .setMethodCallHandler((methodCall) async {
          final args = methodCall.arguments as Map;
          // final refId = args['callerRefId'] as int;
          // if (refId != this.refId) return;
  
          switch (methodCall.method) {
            case 'Callback::com.getkeepsafe.relinker.ReLinker.LoadListener::success':
              // print log
              if (fluttifyLogEnabled) {
                print('fluttify-dart-callback: success([])');
              }
        
              // handle the native call
              var2?.success();
              break;
            default:
              break;
          }
        });
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  static Future<void> loadLibrary__android_content_Context__String__String__com_getkeepsafe_relinker_ReLinker_LoadListener(android_content_Context var0, String var1, String var2, com_getkeepsafe_relinker_ReLinker_LoadListener var3) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.getkeepsafe.relinker.ReLinker::loadLibrary([\'var1\':$var1, \'var2\':$var2])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('com.getkeepsafe.relinker.ReLinker::loadLibrary__android_content_Context__String__String__com_getkeepsafe_relinker_ReLinker_LoadListener', {"var0": var0.refId, "var1": var1, "var2": var2});
  
  
    // handle native call
    MethodChannel('com.getkeepsafe.relinker.ReLinker::loadLibrary__android_content_Context__String__String__com_getkeepsafe_relinker_ReLinker_LoadListener::Callback')
        .setMethodCallHandler((methodCall) async {
          final args = methodCall.arguments as Map;
          // final refId = args['callerRefId'] as int;
          // if (refId != this.refId) return;
  
          switch (methodCall.method) {
            case 'Callback::com.getkeepsafe.relinker.ReLinker.LoadListener::success':
              // print log
              if (fluttifyLogEnabled) {
                print('fluttify-dart-callback: success([])');
              }
        
              // handle the native call
              var3?.success();
              break;
            default:
              break;
          }
        });
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  static Future<com_getkeepsafe_relinker_ReLinkerInstance> force() async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.getkeepsafe.relinker.ReLinker::force([])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('com.getkeepsafe.relinker.ReLinker::force', );
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
      kNativeObjectPool.add(com_getkeepsafe_relinker_ReLinkerInstance()..refId = result..tag = 'hanyin_printer_fluttify');
      return com_getkeepsafe_relinker_ReLinkerInstance()..refId = result..tag = 'hanyin_printer_fluttify';
    }
  }
  
  static Future<com_getkeepsafe_relinker_ReLinkerInstance> log(com_getkeepsafe_relinker_ReLinker_Logger var0) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.getkeepsafe.relinker.ReLinker::log([])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('com.getkeepsafe.relinker.ReLinker::log', );
  
  
    // handle native call
    MethodChannel('com.getkeepsafe.relinker.ReLinker::log::Callback')
        .setMethodCallHandler((methodCall) async {
          final args = methodCall.arguments as Map;
          // final refId = args['callerRefId'] as int;
          // if (refId != this.refId) return;
  
          switch (methodCall.method) {
            case 'Callback::com.getkeepsafe.relinker.ReLinker.Logger::log':
              // print log
              if (fluttifyLogEnabled) {
                print('fluttify-dart-callback: log([\'var1\':$args[var1]])');
              }
        
              // handle the native call
              var0?.log(args['var1']);
              break;
            default:
              break;
          }
        });
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
      kNativeObjectPool.add(com_getkeepsafe_relinker_ReLinkerInstance()..refId = result..tag = 'hanyin_printer_fluttify');
      return com_getkeepsafe_relinker_ReLinkerInstance()..refId = result..tag = 'hanyin_printer_fluttify';
    }
  }
  
  static Future<com_getkeepsafe_relinker_ReLinkerInstance> recursively() async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.getkeepsafe.relinker.ReLinker::recursively([])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('com.getkeepsafe.relinker.ReLinker::recursively', );
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
      kNativeObjectPool.add(com_getkeepsafe_relinker_ReLinkerInstance()..refId = result..tag = 'hanyin_printer_fluttify');
      return com_getkeepsafe_relinker_ReLinkerInstance()..refId = result..tag = 'hanyin_printer_fluttify';
    }
  }
  
  //endregion
}

extension com_getkeepsafe_relinker_ReLinker_Batch on List<com_getkeepsafe_relinker_ReLinker> {
  //region getters
  
  //endregion

  //region methods
  Future<void> loadLibrary__android_content_Context__String_batch(List<android_content_Context> var0, List<String> var1) async {
    // print log
    // if (fluttifyLogEnabled) {
    //   #__log__#
    // }
  
    // invoke native method
    final resultBatch = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('com.getkeepsafe.relinker.ReLinker::loadLibrary__android_content_Context__String_batch', [for (int i = 0; i < this.length; i++) {"var0": var0[i].refId, "var1": var1[i], "refId": this[i].refId}]);
  
  
    // convert native result to dart side object
    if (resultBatch == null) {
      return null;
    } else {
      final typedResult = (resultBatch as List).map((result) => result).toList();
    
      return typedResult;
    }
  }
  
  Future<void> loadLibrary__android_content_Context__String__String_batch(List<android_content_Context> var0, List<String> var1, List<String> var2) async {
    // print log
    // if (fluttifyLogEnabled) {
    //   #__log__#
    // }
  
    // invoke native method
    final resultBatch = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('com.getkeepsafe.relinker.ReLinker::loadLibrary__android_content_Context__String__String_batch', [for (int i = 0; i < this.length; i++) {"var0": var0[i].refId, "var1": var1[i], "var2": var2[i], "refId": this[i].refId}]);
  
  
    // convert native result to dart side object
    if (resultBatch == null) {
      return null;
    } else {
      final typedResult = (resultBatch as List).map((result) => result).toList();
    
      return typedResult;
    }
  }
  
  Future<List<com_getkeepsafe_relinker_ReLinkerInstance>> force_batch() async {
    // print log
    // if (fluttifyLogEnabled) {
    //   #__log__#
    // }
  
    // invoke native method
    final resultBatch = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('com.getkeepsafe.relinker.ReLinker::force_batch', [for (int i = 0; i < this.length; i++) {"refId": this[i].refId}]);
  
  
    // convert native result to dart side object
    if (resultBatch == null) {
      return null;
    } else {
      final typedResult = (resultBatch as List).map((result) => com_getkeepsafe_relinker_ReLinkerInstance()..refId = result..tag = 'hanyin_printer_fluttify').toList();
      kNativeObjectPool.addAll(typedResult);
      return typedResult;
    }
  }
  
  Future<List<com_getkeepsafe_relinker_ReLinkerInstance>> recursively_batch() async {
    // print log
    // if (fluttifyLogEnabled) {
    //   #__log__#
    // }
  
    // invoke native method
    final resultBatch = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('com.getkeepsafe.relinker.ReLinker::recursively_batch', [for (int i = 0; i < this.length; i++) {"refId": this[i].refId}]);
  
  
    // convert native result to dart side object
    if (resultBatch == null) {
      return null;
    } else {
      final typedResult = (resultBatch as List).map((result) => com_getkeepsafe_relinker_ReLinkerInstance()..refId = result..tag = 'hanyin_printer_fluttify').toList();
      kNativeObjectPool.addAll(typedResult);
      return typedResult;
    }
  }
  
  //endregion
}