// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:hanyin_printer_fluttify/src/ios/ios.export.g.dart';
import 'package:hanyin_printer_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

mixin com_getkeepsafe_relinker_ReLinker_Logger on java_lang_Object {
  

  

  

  @mustCallSuper
  Future<void> log(String var1) {
  
  
    if (fluttifyLogEnabled) {
      debugPrint('log::kNativeObjectPool: $kNativeObjectPool');
    }
  }
  
}