// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:hanyin_printer_fluttify/src/ios/ios.export.g.dart';
import 'package:hanyin_printer_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

class com_getkeepsafe_relinker_elf_Elf_Header extends java_lang_Object  {
  //region constants
  static final int ELFCLASS32 = 1;
  static final int ELFCLASS64 = 2;
  static final int ELFDATA2MSB = 2;
  //endregion

  //region creators
  
  //endregion

  //region getters
  Future<bool> get_bigEndian() async {
    final result = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod("com.getkeepsafe.relinker.elf.Elf.Header::get_bigEndian", {'refId': refId});
  
    return result;
  }
  
  Future<int> get_type() async {
    final result = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod("com.getkeepsafe.relinker.elf.Elf.Header::get_type", {'refId': refId});
  
    return result;
  }
  
  Future<int> get_phoff() async {
    final result = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod("com.getkeepsafe.relinker.elf.Elf.Header::get_phoff", {'refId': refId});
  
    return result;
  }
  
  Future<int> get_shoff() async {
    final result = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod("com.getkeepsafe.relinker.elf.Elf.Header::get_shoff", {'refId': refId});
  
    return result;
  }
  
  Future<int> get_phentsize() async {
    final result = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod("com.getkeepsafe.relinker.elf.Elf.Header::get_phentsize", {'refId': refId});
  
    return result;
  }
  
  Future<int> get_phnum() async {
    final result = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod("com.getkeepsafe.relinker.elf.Elf.Header::get_phnum", {'refId': refId});
  
    return result;
  }
  
  Future<int> get_shentsize() async {
    final result = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod("com.getkeepsafe.relinker.elf.Elf.Header::get_shentsize", {'refId': refId});
  
    return result;
  }
  
  Future<int> get_shnum() async {
    final result = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod("com.getkeepsafe.relinker.elf.Elf.Header::get_shnum", {'refId': refId});
  
    return result;
  }
  
  Future<int> get_shstrndx() async {
    final result = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod("com.getkeepsafe.relinker.elf.Elf.Header::get_shstrndx", {'refId': refId});
  
    return result;
  }
  
  //endregion

  //region setters
  Future<void> set_bigEndian(bool bigEndian) async {
    await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('com.getkeepsafe.relinker.elf.Elf.Header::set_bigEndian', {'refId': refId, "bigEndian": bigEndian});
  
  
  }
  
  Future<void> set_type(int type) async {
    await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('com.getkeepsafe.relinker.elf.Elf.Header::set_type', {'refId': refId, "type": type});
  
  
  }
  
  Future<void> set_phoff(int phoff) async {
    await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('com.getkeepsafe.relinker.elf.Elf.Header::set_phoff', {'refId': refId, "phoff": phoff});
  
  
  }
  
  Future<void> set_shoff(int shoff) async {
    await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('com.getkeepsafe.relinker.elf.Elf.Header::set_shoff', {'refId': refId, "shoff": shoff});
  
  
  }
  
  Future<void> set_phentsize(int phentsize) async {
    await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('com.getkeepsafe.relinker.elf.Elf.Header::set_phentsize', {'refId': refId, "phentsize": phentsize});
  
  
  }
  
  Future<void> set_phnum(int phnum) async {
    await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('com.getkeepsafe.relinker.elf.Elf.Header::set_phnum', {'refId': refId, "phnum": phnum});
  
  
  }
  
  Future<void> set_shentsize(int shentsize) async {
    await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('com.getkeepsafe.relinker.elf.Elf.Header::set_shentsize', {'refId': refId, "shentsize": shentsize});
  
  
  }
  
  Future<void> set_shnum(int shnum) async {
    await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('com.getkeepsafe.relinker.elf.Elf.Header::set_shnum', {'refId': refId, "shnum": shnum});
  
  
  }
  
  Future<void> set_shstrndx(int shstrndx) async {
    await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('com.getkeepsafe.relinker.elf.Elf.Header::set_shstrndx', {'refId': refId, "shstrndx": shstrndx});
  
  
  }
  
  //endregion

  //region methods
  Future<com_getkeepsafe_relinker_elf_Elf_SectionHeader> getSectionHeader(int var1) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.getkeepsafe.relinker.elf.Elf.Header@$refId::getSectionHeader([\'var1\':$var1])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('com.getkeepsafe.relinker.elf.Elf.Header::getSectionHeader', {"var1": var1, "refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
      kNativeObjectPool.add(com_getkeepsafe_relinker_elf_Section32Header()..refId = result..tag = 'hanyin_printer_fluttify');
      return com_getkeepsafe_relinker_elf_Section32Header()..refId = result..tag = 'hanyin_printer_fluttify';
    }
  }
  
  Future<com_getkeepsafe_relinker_elf_Elf_ProgramHeader> getProgramHeader(int var1) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.getkeepsafe.relinker.elf.Elf.Header@$refId::getProgramHeader([\'var1\':$var1])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('com.getkeepsafe.relinker.elf.Elf.Header::getProgramHeader', {"var1": var1, "refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
      kNativeObjectPool.add(com_getkeepsafe_relinker_elf_Program32Header()..refId = result..tag = 'hanyin_printer_fluttify');
      return com_getkeepsafe_relinker_elf_Program32Header()..refId = result..tag = 'hanyin_printer_fluttify';
    }
  }
  
  Future<com_getkeepsafe_relinker_elf_Elf_DynamicStructure> getDynamicStructure(int var1, int var3) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: com.getkeepsafe.relinker.elf.Elf.Header@$refId::getDynamicStructure([\'var1\':$var1, \'var3\':$var3])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('com.getkeepsafe.relinker.elf.Elf.Header::getDynamicStructure', {"var1": var1, "var3": var3, "refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
      kNativeObjectPool.add(com_getkeepsafe_relinker_elf_Dynamic64Structure()..refId = result..tag = 'hanyin_printer_fluttify');
      return com_getkeepsafe_relinker_elf_Dynamic64Structure()..refId = result..tag = 'hanyin_printer_fluttify';
    }
  }
  
  //endregion
}

extension com_getkeepsafe_relinker_elf_Elf_Header_Batch on List<com_getkeepsafe_relinker_elf_Elf_Header> {
  //region getters
  Future<List<bool>> get_bigEndian_batch() async {
    final resultBatch = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod("com.getkeepsafe.relinker.elf.Elf.Header::get_bigEndian_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  Future<List<int>> get_type_batch() async {
    final resultBatch = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod("com.getkeepsafe.relinker.elf.Elf.Header::get_type_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  Future<List<int>> get_phoff_batch() async {
    final resultBatch = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod("com.getkeepsafe.relinker.elf.Elf.Header::get_phoff_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  Future<List<int>> get_shoff_batch() async {
    final resultBatch = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod("com.getkeepsafe.relinker.elf.Elf.Header::get_shoff_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  Future<List<int>> get_phentsize_batch() async {
    final resultBatch = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod("com.getkeepsafe.relinker.elf.Elf.Header::get_phentsize_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  Future<List<int>> get_phnum_batch() async {
    final resultBatch = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod("com.getkeepsafe.relinker.elf.Elf.Header::get_phnum_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  Future<List<int>> get_shentsize_batch() async {
    final resultBatch = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod("com.getkeepsafe.relinker.elf.Elf.Header::get_shentsize_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  Future<List<int>> get_shnum_batch() async {
    final resultBatch = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod("com.getkeepsafe.relinker.elf.Elf.Header::get_shnum_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  Future<List<int>> get_shstrndx_batch() async {
    final resultBatch = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod("com.getkeepsafe.relinker.elf.Elf.Header::get_shstrndx_batch", [for (final item in this) {'refId': item.refId}]);
    final typedResult = (resultBatch as List).map((result) => result).toList();
  
    return typedResult;
  }
  
  //endregion

  //region methods
  Future<List<com_getkeepsafe_relinker_elf_Elf_SectionHeader>> getSectionHeader_batch(List<int> var1) async {
    // print log
    // if (fluttifyLogEnabled) {
    //   #__log__#
    // }
  
    // invoke native method
    final resultBatch = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('com.getkeepsafe.relinker.elf.Elf.Header::getSectionHeader_batch', [for (int i = 0; i < this.length; i++) {"var1": var1[i], "refId": this[i].refId}]);
  
  
    // convert native result to dart side object
    if (resultBatch == null) {
      return null;
    } else {
      final typedResult = (resultBatch as List).map((result) => com_getkeepsafe_relinker_elf_Section32Header()..refId = result..tag = 'hanyin_printer_fluttify').toList();
      kNativeObjectPool.addAll(typedResult);
      return typedResult;
    }
  }
  
  Future<List<com_getkeepsafe_relinker_elf_Elf_ProgramHeader>> getProgramHeader_batch(List<int> var1) async {
    // print log
    // if (fluttifyLogEnabled) {
    //   #__log__#
    // }
  
    // invoke native method
    final resultBatch = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('com.getkeepsafe.relinker.elf.Elf.Header::getProgramHeader_batch', [for (int i = 0; i < this.length; i++) {"var1": var1[i], "refId": this[i].refId}]);
  
  
    // convert native result to dart side object
    if (resultBatch == null) {
      return null;
    } else {
      final typedResult = (resultBatch as List).map((result) => com_getkeepsafe_relinker_elf_Program32Header()..refId = result..tag = 'hanyin_printer_fluttify').toList();
      kNativeObjectPool.addAll(typedResult);
      return typedResult;
    }
  }
  
  Future<List<com_getkeepsafe_relinker_elf_Elf_DynamicStructure>> getDynamicStructure_batch(List<int> var1, List<int> var3) async {
    // print log
    // if (fluttifyLogEnabled) {
    //   #__log__#
    // }
  
    // invoke native method
    final resultBatch = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('com.getkeepsafe.relinker.elf.Elf.Header::getDynamicStructure_batch', [for (int i = 0; i < this.length; i++) {"var1": var1[i], "var3": var3[i], "refId": this[i].refId}]);
  
  
    // convert native result to dart side object
    if (resultBatch == null) {
      return null;
    } else {
      final typedResult = (resultBatch as List).map((result) => com_getkeepsafe_relinker_elf_Dynamic64Structure()..refId = result..tag = 'hanyin_printer_fluttify').toList();
      kNativeObjectPool.addAll(typedResult);
      return typedResult;
    }
  }
  
  //endregion
}