// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

import 'dart:typed_data';

import 'package:hanyin_printer_fluttify/src/ios/ios.export.g.dart';
import 'package:hanyin_printer_fluttify/src/android/android.export.g.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

class PRTAndroidSDKA300_CheckPrinter extends java_lang_Object  {
  //region constants
  
  //endregion

  //region creators
  static Future<PRTAndroidSDKA300_CheckPrinter> create__android_content_Context__byteArray__byteArray__String(android_content_Context var1, Uint8List var2, Uint8List var3, String var4) async {
    final int refId = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('ObjectFactory::createPRTAndroidSDKA300_CheckPrinter__android_content_Context__byteArray__byteArray__String', {"var1": var1.refId, "var2": var2, "var3": var3, "var4": var4});
    final object = PRTAndroidSDKA300_CheckPrinter()..refId = refId..tag = 'hanyin_printer_fluttify';
  
    kNativeObjectPool.add(object);
    return object;
  }
  
  static Future<List<PRTAndroidSDKA300_CheckPrinter>> create_batch__android_content_Context__byteArray__byteArray__String(List<android_content_Context> var1, List<Uint8List> var2, List<Uint8List> var3, List<String> var4) async {
    // if (#__check_param_size__#) {
    //   return Future.error('all args must has same length!');
    // }
    final List resultBatch = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('ObjectFactory::create_batchPRTAndroidSDKA300_CheckPrinter__android_content_Context__byteArray__byteArray__String', [for (int i = 0; i < var1.length; i++) {"var1": var1[i].refId, "var2": var2[i], "var3": var3[i], "var4": var4[i]}]);
  
    final List<PRTAndroidSDKA300_CheckPrinter> typedResult = resultBatch.map((result) => PRTAndroidSDKA300_CheckPrinter()..refId = result..tag = 'hanyin_printer_fluttify').toList();
    kNativeObjectPool.addAll(typedResult);
    return typedResult;
  }
  
  //endregion

  //region getters
  
  //endregion

  //region setters
  
  //endregion

  //region methods
  Future<void> MD5CheckPrinter(Uint8List var1, Uint8List var2) async {
    // print log
    if (fluttifyLogEnabled) {
      print('fluttify-dart: PRTAndroidSDKA300.CheckPrinter@$refId::MD5CheckPrinter([\'var1\':$var1, \'var2\':$var2])');
    }
  
    // invoke native method
    final result = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('PRTAndroidSDKA300.CheckPrinter::MD5CheckPrinter', {"var1": var1, "var2": var2, "refId": refId});
  
  
    // handle native call
  
  
    // convert native result to dart side object
    if (result == null) {
      return null;
    } else {
    
      return result;
    }
  }
  
  //endregion
}

extension PRTAndroidSDKA300_CheckPrinter_Batch on List<PRTAndroidSDKA300_CheckPrinter> {
  //region getters
  
  //endregion

  //region methods
  Future<void> MD5CheckPrinter_batch(List<Uint8List> var1, List<Uint8List> var2) async {
    // print log
    // if (fluttifyLogEnabled) {
    //   #__log__#
    // }
  
    // invoke native method
    final resultBatch = await MethodChannel('me.yohom/hanyin_printer_fluttify').invokeMethod('PRTAndroidSDKA300.CheckPrinter::MD5CheckPrinter_batch', [for (int i = 0; i < this.length; i++) {"var1": var1[i], "var2": var2[i], "refId": this[i].refId}]);
  
  
    // convert native result to dart side object
    if (resultBatch == null) {
      return null;
    } else {
      final typedResult = (resultBatch as List).map((result) => result).toList();
    
      return typedResult;
    }
  }
  
  //endregion
}