// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum PTCPCLQRCodeUnitWidth {
  PTCPCLQRCodeUnitWidth_1,
  PTCPCLQRCodeUnitWidth_2,
  PTCPCLQRCodeUnitWidth_3,
  PTCPCLQRCodeUnitWidth_4,
  PTCPCLQRCodeUnitWidth_5,
  PTCPCLQRCodeUnitWidth_6,
  PTCPCLQRCodeUnitWidth_7,
  PTCPCLQRCodeUnitWidth_8,
  PTCPCLQRCodeUnitWidth_9,
  PTCPCLQRCodeUnitWidth_10,
  PTCPCLQRCodeUnitWidth_11,
  PTCPCLQRCodeUnitWidth_12,
  PTCPCLQRCodeUnitWidth_13,
  PTCPCLQRCodeUnitWidth_14,
  PTCPCLQRCodeUnitWidth_15,
  PTCPCLQRCodeUnitWidth_16,
  PTCPCLQRCodeUnitWidth_17,
  PTCPCLQRCodeUnitWidth_18,
  PTCPCLQRCodeUnitWidth_19,
  PTCPCLQRCodeUnitWidth_20,
  PTCPCLQRCodeUnitWidth_21,
  PTCPCLQRCodeUnitWidth_22,
  PTCPCLQRCodeUnitWidth_23,
  PTCPCLQRCodeUnitWidth_24,
  PTCPCLQRCodeUnitWidth_25,
  PTCPCLQRCodeUnitWidth_26,
  PTCPCLQRCodeUnitWidth_27,
  PTCPCLQRCodeUnitWidth_28,
  PTCPCLQRCodeUnitWidth_29,
  PTCPCLQRCodeUnitWidth_30,
  PTCPCLQRCodeUnitWidth_31,
  PTCPCLQRCodeUnitWidth_32
}