// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum PTCPCLTextFontName {
  PTCPCLTextFont1,
  PTCPCLTextFont2,
  PTCPCLTextFont3,
  PTCPCLTextFont4,
  PTCPCLTextFont5,
  PTCPCLTextFont7,
  PTCPCLTextFont8,
  PTCPCLTextFont20,
  PTCPCLTextFont28,
  PTCPCLTextFont55
}