// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum PTCPCLBarcodeBarRatio {
  PTCPCLBarcodeBarRatio0,
  PTCPCLBarcodeBarRatio1,
  PTCPCLBarcodeBarRatio2,
  PTCPCLBarcodeBarRatio3,
  PTCPCLBarcodeBarRatio4,
  PTCPCLBarcodeBarRatio20,
  PTCPCLBarcodeBarRatio21,
  PTCPCLBarcodeBarRatio22,
  PTCPCLBarcodeBarRatio23,
  PTCPCLBarcodeBarRatio24,
  PTCPCLBarcodeBarRatio25,
  PTCPCLBarcodeBarRatio26,
  PTCPCLBarcodeBarRatio27,
  PTCPCLBarcodeBarRatio28,
  PTCPCLBarcodeBarRatio29,
  PTCPCLBarcodeBarRatio30
}