// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum PTTSCPrintDensity {
  PTTSCPrintDensity0,
  PTTSCPrintDensity1,
  PTTSCPrintDensity2,
  PTTSCPrintDensity3,
  PTTSCPrintDensity4,
  PTTSCPrintDensity5,
  PTTSCPrintDensity6,
  PTTSCPrintDensity7,
  PTTSCPrintDensity8,
  PTTSCPrintDensity9,
  PTTSCPrintDensity10,
  PTTSCPrintDensity11,
  PTTSCPrintDensity12,
  PTTSCPrintDensity13,
  PTTSCPrintDensity14,
  PTTSCPrintDensity15
}