// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum PTTSCTextVectorFontStyle {
  PTTSCTextVectorFontStyle0,
  PTTSCTextVectorFontStyle1,
  PTTSCTextVectorFontStyle2,
  PTTSCTextVectorFontStyle3,
  PTTSCTextVectorFontStyle4,
  PTTSCTextVectorFontStyle5,
  PTTSCTextVectorFontStyle6,
  PTTSCTextVectorFontStyle7,
  PTTSCTextVectorFontStyle8,
  PTTSCTextVectorFontStyle9
}