// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum PTTSCQRcodeMask {
  PTTSCQRcodeMaskS0,
  PTTSCQRcodeMaskS1,
  PTTSCQRcodeMaskS2,
  PTTSCQRcodeMaskS3,
  PTTSCQRcodeMaskS4,
  PTTSCQRcodeMaskS5,
  PTTSCQRcodeMaskS6,
  PTTSCQRcodeMaskS7,
  PTTSCQRcodeMaskS8
}