// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum PTZplFont {
  PTZplFont0,
  PTZplFont1,
  PTZplFontA,
  PTZplFontB,
  PTZplFontC,
  PTZplFontD,
  PTZplFontE,
  PTZplFontF,
  PTZplFontG,
  PTZplFontH,
  PTZplFontI
}