// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum PTZplCode128Mode {
  PTZplCode128Mode_N,
  PTZplCode128Mode_U,
  PTZplCode128Mode_A,
  PTZplCode128Mode_D
}