// ignore_for_file: non_constant_identifier_names, camel_case_types, missing_return, unused_import, unused_local_variable
//////////////////////////////////////////////////////////
// GENERATED BY FLUTTIFY. DO NOT EDIT IT.
//////////////////////////////////////////////////////////

enum PTZplQrReliabilityLevel {
  PTZplQrReliabilityLevel_H,
  PTZplQrReliabilityLevel_Q,
  PTZplQrReliabilityLevel_M,
  PTZplQrReliabilityLevel_L
}